name: template-flask-app

services:
- name: api
  environment_slug: python
  github:
    repo: digitalocean/template-flask-app
    branch: main
    deploy_on_push: true
  source_dir: /
  envs:
    - key: VALKEY_URL
      value: <REQUIRED>

workers:
- name: worker
  environment_slug: python
  github:
    repo: digitalocean/template-flask-app
    branch: main
    deploy_on_push: true
  envs:
  - key: VALKEY_URL
    value: <REQUIRED>
  run_command: celery -A api.tasks.celery worker --loglevel=info
